solarmax:
  clientIp: 192.168.1.123
  clientPort: 12345
  request:
   - PAC
   - TKK
   - KDY
   - UL1
  cron: '0 0/5 6-23 * * *'

pvoutput:
  host: https://pvoutput.org
  cron: '5 0/2 6-23 * * *'

spring:
  devtools:
    add-properties: false

logging:
  path: logs
  file: ${logging.path}/solarmax.log
  pattern.file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
